#AQUI HAY QUE ESCRIBIR LAS CONSTANTES DE TEXTO GENERALES 
#REPOS

REPO_URL = ""

#CURSOS

PYTHON_COURSE_URL = ""
SQL_COURSE_URL = ""
GIT_COURSE_URL = ""
LANGUAGES_COURSE_URL = ""
CODE_CHALLENGE_URL =""
COFFE_URL = ""